import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Headertop from "@/components/Headertop";
import Header from "@/components/Header";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className={inter.className}>
        <Headertop />
        <Header />
        {children}
        <Footer/>
        </body>
    </html>
  );
}
